### ISSUE TITLE
Incompatible with Rails 4.1

### ISSUE THREAD

**Issue by raphaelcm** [joshuajansen/magnific-popup-rails#6]
Just upgraded to Rails 4.1, and this gem doesn't work.

```
Sass::SyntaxError - File to import not found or unreadable: magnific-popup.
Load paths:
  /Users/raphael/Documents/projects/special_sauce/app/assets/images
  /Users/raphael/Documents/projects/special_sauce/app/assets/javascripts
  /Users/raphael/Documents/projects/special_sauce/app/assets/stylesheets
  /Users/raphael/Documents/projects/special_sauce/vendor/assets/javascripts
  /Users/raphael/Documents/projects/special_sauce/vendor/assets/stylesheets
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-2.3.2.2/vendor/assets/images
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-2.3.2.2/vendor/assets/javascripts
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-2.3.2.2/vendor/assets/stylesheets
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/coffee-rails-4.1.0/lib/assets/javascripts
  /Users/raphael/.rvm/gems/ruby-2.1.1/bundler/gems/rails_emoji-ab58de3a497a/vendor/assets/images
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/magnific-popup-rails-0.9.9/vendor/assets/javascripts
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/magnific-popup-rails-0.9.9/vendor/assets/stylesheets
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/jquery-form-rails-1.0.1/vendor/assets/javascripts
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/jquery-rails-3.1.2/vendor/assets/javascripts
  /Users/raphael/.rvm/gems/ruby-2.1.1/gems/d3-rails-3.4.13/app/assets/javascripts
  /Users/raphael/Documents/projects/vendor/assets/stylesheets
  (in /Users/raphael/Documents/projects/special_sauce/app/assets/stylesheets/application.css.scss:40):
  sass (3.2.19) lib/sass/tree/import_node.rb:67:in `rescue in import'
  sass (3.2.19) lib/sass/tree/import_node.rb:45:in `import'
  sass (3.2.19) lib/sass/tree/import_node.rb:28:in `imported_file'
  sass (3.2.19) lib/sass/tree/import_node.rb:37:in `css_import?'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:217:in `visit_import'
  sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `visit'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:100:in `visit'
  sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  sass (3.2.19) lib/sass/tree/visitors/base.rb:53:in `visit_children'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:121:in `with_environment'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:108:in `visit_children'
  sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `block in visit'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:128:in `visit_root'
  sass (3.2.19) lib/sass/tree/visitors/base.rb:37:in `visit'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:100:in `visit'
  sass (3.2.19) lib/sass/tree/visitors/perform.rb:7:in `visit'
  sass (3.2.19) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.2.19) lib/sass/engine.rb:315:in `_render'
  sass (3.2.19) lib/sass/engine.rb:262:in `render'
  sass-rails (4.0.4) lib/sass/rails/template.rb:22:in `evaluate'
```

Any ideas?

**Comment by sheharyarn** [comment]
I'm using version `0.9.9.1` of this gem and still get this error when precompiling assets for production (manually and using capistrano).

```
Sass::SyntaxError: File to import not found or unreadable: magnific-popup/magnific-popup.
Load paths:
  /Users/Psycho/code/myrailsapp/app/assets/fonts
  /Users/Psycho/code/myrailsapp/app/assets/images
  /Users/Psycho/code/myrailsapp/app/assets/javascripts
  /Users/Psycho/code/myrailsapp/app/assets/stylesheets
  /Users/Psycho/code/myrailsapp/vendor/assets/javascripts
  /Users/Psycho/code/myrailsapp/vendor/assets/stylesheets
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/magnific-popup-rails-0.9.9.1/vendor/assets/javascripts
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/magnific-popup-rails-0.9.9.1/vendor/assets/stylesheets
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/font-awesome-rails-4.3.0.0/app/assets/fonts
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/font-awesome-rails-4.3.0.0/app/assets/stylesheets
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/turbolinks-2.5.3/lib/assets/javascripts
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/jquery-rails-4.0.3/vendor/assets/javascripts
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/nprogress-rails-0.1.6.6/app/assets/javascripts
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/nprogress-rails-0.1.6.6/app/assets/stylesheets
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/twitter-bootswatch-rails-3.2.0.0/app/assets/fonts
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/twitter-bootswatch-rails-3.2.0.0/app/assets/javascripts
  /Users/Psycho/code/myrailsapp/vendor/pages
  /Users/Psycho/code/myrailsapp/app/assets/fonts
  /Users/Psycho/.rvm/gems/ruby-2.2.0/gems/twitter-bootswatch-rails-3.2.0.0/vendor/toolkit
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/import_node.rb:64:in `import'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/import_node.rb:28:in `imported_file'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/import_node.rb:37:in `css_import?'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:311:in `visit_import'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `block in with_base'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:157:in `visit'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/root_node.rb:36:in `css_tree'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/tree/root_node.rb:20:in `render'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/engine.rb:268:in `render'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/sass_template.rb:53:in `evaluate'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:105:in `each'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:16:in `initialize'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `each'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `compile'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/Psycho/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/Psycho/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/Psycho/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by sheharyarn** [comment]
As a temporary fix, I've copied the [css file](https://github.com/joshuajansen/magnific-popup-rails/blob/master/vendor/assets/stylesheets/magnific-popup/magnific-popup.css) to my `vendor` directory.

**Comment by kylesnowschwartz** [comment]
> As a temporary fix, I've copied the [css file](https://github.com/joshuajansen/magnific-popup-rails/blob/master/vendor/assets/stylesheets/magnific-popup/magnific-popup.css) to my `vendor` directory.

You might be importing like so:
`@import magnific-popup/magnific-popup`

Try just `@import magnific-popup`
